FROM node:alpine
ENV FRONT_URL=http://localhost:5000
EXPOSE 8000

WORKDIR /backend-example-docker

RUN apk add git --no-cache && \
    git clone https://github.com/docker-hy/backend-example-docker.git /backend-example-docker && \
    npm install && \
    npm cache rm --force && \
    apk del git && \
    chown -R node /backend-example-docker && \
    chmod -R u+x /backend-example-docker
    
USER node

CMD npm start