FROM node:alpine
ENV API_URL=http://localhost:8000
EXPOSE 5000

WORKDIR /frontend-example-docker

RUN apk add git --no-cache && \
    git clone https://github.com/docker-hy/frontend-example-docker.git /frontend-example-docker && \
    npm install && \
    npm cache rm --force && \
    apk del git && \
    chown -R node /frontend-example-docker && \
    chmod -R u+x /frontend-example-docker

USER node

CMD npm start