
version: '3.5'

services:
    backend:
        # Works either way, with a prebuilt image or by building the frontend here
        image: 'backend'
        #build:
        #    ./backend-example-docker
        environment:
            - REDIS=redis
            - DB_HOST=postgres
            - DB_NAME=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=example
        ports:
            - 8000:8000
        depends_on: 
            - postgres
        volumes:
            - ./logs.txt:/usr/app/logs.txt
        container_name: backend
        tty: true
        command: npm start
    
    frontend:
        # Works either way, with a prebuilt image or by building the frontend here
        image: 'frontend'
        #build:
        #    ./frontend-example-docker
        environment:
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
        container_name: frontend
        tty: true
        command: npm start
    
    redis:
        image: 'redis'
        volumes:
            - ./redis_data:/data

    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./database:/var/lib/postgresql/data

    nginx:
        image: nginx
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        ports:
            - 80:80
        container_name: nginx
        depends_on:
            - frontend
            - backend
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        restart: always
    


