
version: '3.5'

services:
    backend:
        image: 'backend'
        environment:
            - FRONT_URL=http://localhost:5000
        ports:
            - 8000:8000
        volumes:
            - ./logs.txt:/usr/app/logs.txt
        container_name: backend
        tty: true
        command: npm start
    
    frontend:
        image: 'frontend'
        environment:
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
        container_name: frontend
        tty: true
        command: npm start