FROM ubuntu:16.04

WORKDIR /mydir
COPY . .

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get -y install nodejs

RUN node -v && npm -v

# This was commented out in 2.10. API_URL is now defined in docker-compose.yml
#ENV API_URL=http://localhost:8000
RUN npm install

EXPOSE 5000

ENTRYPOINT npm start

