FROM ubuntu:16.04

WORKDIR /backend-example-docker

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    apt-get purge -y --autoremove curl && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000
ENV FRONT_URL=http://localhost:5000
ENTRYPOINT npm start